version: '2'
services:
    shadowsocks:
      build:
        context: .
      entrypoint:
        - /entrypoint.sh
        - -m
        - "ss-server"
        - -s
        - "-s 0.0.0.0 -p 6443 -m aes-256-cfb -k test123 --fast-open"
        - -x
        - -e
        - "kcpserver"
        - -k
        - "-t 127.0.0.1:6443 -l :6500 -mode fast2"
      ports:
        - 6443:6443
        - 6500:6500/udp
